### ISSUE TITLE
undefined variable error in /lib/OperatingSystems/DefaultOs.php #173

### ISSUE THREAD

**Issue by HeekangPark** [nextcloud/serverinfo#184] opened 2020-03-18 10:28 UTC
Hi, I downloaded Nextcloud via `snap` in my laptop with Ubuntu Desktop 18.04.4 LTS installed. On Settings-System tab, it seems like Nextcloud cannot fetch OS.

![image](https://user-images.githubusercontent.com/16741548/76963489-72afee80-6964-11ea-9329-1adc5c48bf84.png)

And I can see undefined variable error on the system log.

![image](https://user-images.githubusercontent.com/16741548/76951052-615be780-694e-11ea-937b-331a894dd7eb.png)

I haven't use php, so I'm not sure what I'm saying, but I believe variable `$result` should be initialized before it is used in `foreach`. Can you please check this error out?

Thank you in advance.

**Comment by J0WI** [comment] 2020-05-10 11:17
Duplicate of #168

**Closed by J0WI** 2020-05-10 11:17 UTC
