### ISSUE TITLE
Php error

### ISSUE THREAD

**Issue by jookk** [nextcloud/serverinfo#156] opened 2019-09-30 14:39 UTC
Nc 17rc2
Php7.3
Apache2.4

Invalid argument supplied for foreach() at /var/www/ours.orencak.sk/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#120

**Comment by J0WI** [comment] 2020-05-10 11:16
Duplicate of #168

**Closed by J0WI** 2020-05-10 11:16 UTC
